name: Build documentation

on:
  push:
    branches:
      - use_py310_for_docbuild

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@use_py_310
    with:
      commit_sha: ${{ github.sha }}
      package: transformers
      notebook_folder: transformers_doc
      languages: de en es fr hi it ko pt tr zh ja te
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
